# Auto-generated by alloy-codegen — do not edit.
# Top-level CMake meta-package (added by ``add-cmake-package-config``).
#
# Resolves find_package(AlloyDevice REQUIRED COMPONENTS <device>...)
# by including the per-device AlloyDevice-<device>.cmake module from
# the matching vendor/family sub-directory.

if(NOT DEFINED ALLOY_DEVICE_ROOT)
  get_filename_component(ALLOY_DEVICE_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()

set(_ALLOY_DEVICE_COMPONENT_PATHS
  "atsame70n21b=microchip/same70/generated/cmake/AlloyDevice-atsame70n21b.cmake"
  "atsame70q21b=microchip/same70/generated/cmake/AlloyDevice-atsame70q21b.cmake"
)

foreach(component ${AlloyDevice_FIND_COMPONENTS})
  set(_alloy_found FALSE)
  foreach(entry ${_ALLOY_DEVICE_COMPONENT_PATHS})
    string(REPLACE "=" ";" parts ${entry})
    list(GET parts 0 _name)
    list(GET parts 1 _path)
    if(_name STREQUAL component)
      include("${ALLOY_DEVICE_ROOT}/${_path}")
      set(_alloy_found TRUE)
      break()
    endif()
  endforeach()
  if(NOT _alloy_found)
    set(AlloyDevice_${component}_FOUND FALSE)
    if(AlloyDevice_FIND_REQUIRED_${component})
      message(FATAL_ERROR "AlloyDevice: unknown component \"${component}\"")
    endif()
  else()
    set(AlloyDevice_${component}_FOUND TRUE)
  endif()
endforeach()

set(AlloyDevice_FOUND TRUE)
